#pragma once

#define GAME_ICON_PATH "Engine Images/Pixal Engine Logo.png"
#define ENGINE_FONT_PATH "Engine Font/VT323-Regular.ttf"
#define ENGINE_BACKGROUND "Engine Images/EngineBackground.png"
#define ENGINE_BACKGROUND_SCALE 3.f

// Code Block Data //
#define CODE_BLOCK_TILE_SIZE 32
#define CODE_BLOCK_HEIGHT 3
#define CODE_BLOCK_SHEET_TEXT_SEGMENT 2
#define CODE_BLOCK_SHEET_END_SEGMENT 6
#define CODE_BLOCK_PARAMETER_SEGMENT_SIZE 4
#define CODE_BLOCK_SHEET_PARAMETER_SEGMENT_Y 3
#define CODE_BLOCK_SHEET_PARAMETER_SEGMENT_X 3
#define CODE_BLOCK_SHEET_TAIL_SEGMENT 0,4
#define CODE_BLOCK_CONDITIONAL_TAIL_LENGTH 2
#define CODE_BLOCK_SHEET_TAIL_END_Y 5

// Colours //
#define COLOUR_BLUE {100,100,255,255}
#define COLOUR_GREEN {100,255,100,255}
#define COLOUR_RED {255,100,100,255}
#define COLOUR_YELLOW {255,255,100,255}
#define COLOUR_WHITE {255,255,255,255}
#define COLOUR_LIGHT_GREY {200,200,200,255}


#define ZOOM_SENSITIVITY 0.25f

// Engine Screen Dimensions //
#define ENGINE_SCREEN_WIDTH 1080
#define ENGINE_SCREEN_HEIGHT 720

// Game Screen Dimensions //
#define GAME_SCREEN_WIDTH 1080
#define GAME_SCREEN_HEIGHT 720